# For C
CC = gcc
TARGET = main
SRCS = Twins.c

#all: clean $(TARGET)

#$(TARGET): $(SRCS)
#	$(CC) $(SRCS) -o $(TARGET)

#clean:
#	rm -f $(TARGET)


#######################


# For java
all:
	javac Even_Odds.java
	java Even_Odds

clean:
	rm -f *.class




