# For C
CC = gcc
TARGET = main
SRCS = Brain_Photos.c
FLAGS = -Wextra -Wall

all: clean $(TARGET)

$(TARGET): $(SRCS)
	$(CC) $(FLAGS) $(SRCS) -o $(TARGET)

clean:
	rm -f $(TARGET)


#######################


# For java
#all:
#	javac Even_Odds.java
#	java Even_Odds

#clean:
#	rm -f *.class




